import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4200/home');
  await page.getByRole('button', { name: 'General General infos' }).click();
  await page.getByText('Edit an existing questionnaire').click();
  await page.getByRole('combobox', { name: 'Number' }).click();
  await page.getByRole('combobox', { name: 'Number' }).fill('test11');
  await page.getByText('test11', { exact: true }).click();
  await page.locator('#mat-select-value-1').click();
  await page.getByText('Dutch').click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.getByRole('button', { name: 'save' }).click();
  await page.locator('#mat-select-value-1').click();
  await page.getByRole('option', { name: 'Dutch' }).click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.getByRole('button', { name: 'save' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Header All about the header' }).click();
  await page.getByRole('textbox', { name: 'English: Quest Title' }).click();
  await page.getByRole('textbox', { name: 'English: Quest Title' }).fill('');
  await page.getByRole('button', { name: 'Footer Footer in' }).click();
  await page.getByRole('region', { name: 'Footer Footer in' }).getByLabel('').click();
  await page.getByRole('button', { name: 'Result What is shown in the' }).click();
  await page.locator('iframe[title="Rich Text Area"]').contentFrame().getByText('test').click();
  await page.locator('iframe[title="Rich Text Area"]').contentFrame().getByText('test').fill('test bla');
//   await page.locator('#tiny-angular_81702685411739800675687_ifr').contentFrame().getByText('test').click();
//   await page.locator('#tiny-angular_36849921811739800539529_ifr').contentFrame().getByLabel('Rich Text Area. Press ALT-0').fill('testdrgdrgdrgffff\n\n\n\n\ndrgdrgdrg');
  await page.getByText('radar, doughnut, polar, bar').click();
  await page.getByText('doughnut', { exact: true }).click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.getByRole('button', { name: 'Finish Last things to do' }).click();
  await page.getByRole('button', { name: 'save and create' }).click();
  await page.getByRole('button', { name: 'General General infos' }).click();
  await page.getByText('Mode').click();
  await page.getByText('Delete a questionnaire').click();
  await page.waitForTimeout(3000);
  await page.getByRole('combobox', { name: 'Number' }).click();
  await page.getByRole('combobox', { name: 'Number' }).fill('test11__invalid');
//   await page.getByText('test11__invalid').click();
    await page.getByText('test11__invalid', { exact: true }).click();
//   await page.locator('.mat-option >> text="test11__invalid"').click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.waitForTimeout(3000);

//   await page.getByRole('button', { name: 'General General infos' }).click();
  await page.getByText('Edit an existing questionnaire').click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('combobox', { name: 'Number' }).click();
  await page.getByRole('combobox', { name: 'Number' }).fill('test11');
  await page.getByText('test11', { exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Header All about the header' }).click();
  await page.getByRole('textbox', { name: 'English: Quest Title' }).click();
  await page.getByRole('textbox', { name: 'English: Quest Title' }).fill('test');
  await page.getByRole('button', { name: 'Finish Last things to do' }).click();
  await page.locator('[formcontrolname="questionnaireFileName"]').click();
  await page.locator('[formcontrolname="questionnaireFileName"]').fill('test11_1');
  await page.getByRole('button', { name: 'save and create' }).click();
  await page.waitForTimeout(3000);
  await page.getByRole('button', { name: 'General General infos' }).click();
  await page.getByText('Mode').click();
  await page.getByText('Edit an existing questionnaire').click();
  await page.getByRole('tab', { name: 'Editable Choose' }).click();
  await page.getByRole('combobox', { name: 'Number' }).click();
  await page.getByRole('combobox', { name: 'Number' }).fill('test11_1');
  await page.getByText('test11_1', { exact: true }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Header All about the header' }).click();
  await expect(page.getByRole('textbox', { name: 'English: Quest Title' })).toHaveValue('test');
  await page.getByRole('button', { name: 'General General infos' }).click();
  await page.getByText('Mode').click();
  await page.getByText('Delete a questionnaire').click();
//   await page.locator('div').filter({ hasText: /^Pick one \*$/ }).nth(2).click();
  await page.getByRole('combobox', { name: 'Number' }).fill('test11_1');
  await page.getByText('test11_1', { exact: true }).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.waitForTimeout(3000);
});